Default on ReplaceOptions.hint is missing
So it'll throw a not very helpful error at you:
`error[E0599]: no method named `build` found for type `mongodb::coll::options::TypedBuilder_BuilderFor_ReplaceOptions<(), (std::option::Option<bool>,), (), (), ()>` in the current scope`